all :  gen0 gen1 gen2 gen3 gen4 gen5 gen6 gen7 gen8 gen9

gen0: generator0.cc
	g++ -Wall -g -std=c++11 generator0.cc  -o generator0

gen1: generator1.cc
	g++ -Wall -g -std=c++11 generator1.cc  -o generator1

gen2: generator2.cc
	g++ -Wall -g -std=c++11 generator2.cc  -o generator2

gen3: generator3.cc
	g++ -Wall -g -std=c++11 generator3.cc  -o generator3

gen4: generator4.cc
	g++ -Wall -g -std=c++11 generator4.cc  -o generator4

gen5: generator5.cc
	g++ -Wall -g -std=c++11 generator5.cc  -o generator5

gen6: generator6.cc
	g++ -Wall -g -std=c++11 generator6.cc  -o generator6

gen7: generator7.cc
	g++ -Wall -g -std=c++11 generator7.cc  -o generator7

gen8: generator8.cc
	g++ -Wall -g -std=c++11 generator8.cc  -o generator8

gen9: generator9.cc
	g++ -Wall -g -std=c++11 generator9.cc  -o generator9

clean:
	rm generator0
	rm generator1
	rm generator2
	rm generator3
	rm generator4
	rm generator5
	rm generator6
	rm generator7
	rm generator8
	rm generator9
	